### ISSUE TITLE
EventualResult.wait() can add up to 50ms of latency in Python <3.2

### ISSUE THREAD

**Issue by jnb** [itamarst/crochet#103]
Condition variables in versions of Python earlier than 3.2 use `sleep()` with an exponential backoff for the `wait()` method.  The maximum backoff value is 50ms, meaning that there can be up to 50ms of latency between `notify()`ing a condition variable and a `wait()` returning:

https://hg.python.org/cpython/file/2.6/Lib/threading.py#l243

This is problematic because `EventualResult` uses a condition variable to signal completion (via `threading.Event`), leading to up to 50ms of additional latency.  We've observed this performance issue in production.

**Comment by itamarst** [comment]
Thanks for the bug report. My first thought is that easiest solution is just to wake up every 1ms... busy polling, but not *too* busy.

**Comment by itamarst** [comment]
Second thought: self-pipe trick, `select()` and friends have nice timeout capabilities without busy waiting.

Third thought: call `sem_timedwait` like Python 3 does.

**Comment by itamarst** [comment]
Option 1 uses some amount of CPU (at least for 1ms, 5ms max latency may be OK.) Option 2 uses two file descriptors per `EventualResult`, which isn't great since they're limited resource also used for network connections and files. Option 3 seems like a bunch of work.

What latency would you consider acceptable?

**Comment by itamarst** [comment]
@jnb -^

**Comment by jnb** [comment]
Somewhere around 1ms latency is probably OK, although I'm worried about burning CPU time.

I'm currently playing with the `sem_timedwait` option :)

**Comment by itamarst** [comment]
Cool, let me know how that goes, I'd love to have a patch.

**Comment by itamarst** [comment]
At this point I don't care about Python older than 3.5 or so, though support for Python 2.7 will continue. So closing.
