### ISSUE TITLE
UPDATED: document that non-Twisted thread shouldn't call Twisted API

### ISSUE THREAD

**Issue by bpicolo** [itamarst/crochet#104]
So, pretty sure I've sort-of narrowed this down at this point.

This looping call: https://github.com/itamarst/crochet/blob/master/crochet/_eventloop.py#L335
seems to be preventing twisted from spawning new TCP connections, which suggests it's blocking in some way. 

Here's an example blown up to a delay of 3s:

```
Got 200 in 15ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 3ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 3ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 3ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 2986ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 4ms using <class 'bravado_promised.twisted_client.TwistedClient'>
Got 200 in 4ms using <class 'bravado_promised.twisted_client.TwistedClient'>
```

Meanwhile, if I see the call to loop every .1ms the issue disappears. I'm not entirely sure why this stops twisted from doing other work. 

This is on ubuntu 10.04

**Comment by itamarst** [comment]
For reference, issue seemed to be calling Twisted APIs from non-Twisted threads. Resulting work was therefore not noticed by Twisted event loop until it was woken up by the reapAllProcesses LoopingCall.

Possibly this restriction should be documented better.

**Comment by itamarst** [comment]
Done.
