### ISSUE TITLE
MemoryErrors when logging handlers raise exceptions

### ISSUE THREAD

**Issue by schlenk** [itamarst/crochet#108]
This lets a python 2.7.11 + twisted 14.0 + crochet 1.4 (win32, 32-Bit) grow to 2 GB in size, and be pretty much disfunctional for anything (but not crashing sometimes, only raising a MemoryError if lucky). It also has the same effect for Twisted 17.1.

    import time
    import crochet
    import logging

    class BrokenHandler(logging.Handler):
        def emit(self, record):
             raise ValueError("Kaboom")

    log = logging.getLogger("twisted")
    h = BrokenHandler(logging.DEBUG)
    log.addHandler(h)
    log.setLevel(logging.DEBUG)

    crochet.setup()
    while 1:
         time.sleep(10)

It should not hang like that, even if the logger misbehaves.

**Comment by itamarst** [comment]
Sorry about that, I'll take a look and see if there's anything I can do this weekend.

What would be your preferred behavior? Just dropping log messages on the floor seems like one option.

**Comment by schlenk** [comment]
yes, simply dropping them is probably the way to go. 

At least on windows when running as a GUI app or service there isn't any sys.stderr to fallback to, so printing to sys.stderr unconditionally is out.

**Comment by itamarst** [comment]
OK, I think I've figured out the problem, will try to implement a fix next.

**Comment by itamarst** [comment]
This is now fixed in Crochet 1.7.0. Thanks again for the bug report!

**Comment by schlenk** [comment]
thx for fixing this quickly AND doing a release
