### ISSUE TITLE
crochet.setup() interacts badly with fork()-without-exec()

### ISSUE THREAD

**Issue by bobbyrussell** [itamarst/crochet#71]
crochet.setup() appears not to set up the reactor in certain cases. Consider the following code:

    # tasks.py
    ...
    import os
    # set up celery...
    from celery import group
    from twisted.internet import reactor, ProcessProtocol
    from crochet import setup, wait_for
    setup()
    ...

    @app.task('tasks.enqueue')
    def enqueue(script_name, command):
        try:
            proc = ProcessProtocol()
            proc.deferred.addCallBack(lamda x: x)
            env = os.environ.copy()
            prints "About to run async process"
            run_async_process(proc, script_name, command, env)
            return proc.exitcode
        except Exception as e:
            print e
        

    @wait_for(timeout=100.0)
    def run_async_process(proc, script_name, command, env):
        pid = reactor.spawnProcess(proc, script_name, command, env)
        print "Process Spawned with PID {}".format(pid)
        # return the deferred when computation ends
        return proc.deferred

    @app.task(name='tasks.fails')
    def fails(script_name, command):
        group(enqueue.si(script_name, command))()
        
    # test.py
    from tasks import enqueue, fails

    print "Prints expected results"
    enqueue('/usr/bin/echo', ['/usr/bin/echo', 'hello'])

    print "Prints nothing"
    fails('/usr/bin/echo', ['/usr/bin/echo', 'hello'])

The first task returns what is excepted. The second task hangs just after printing "About to run async process," and the body of run_async_process() never executes. In the second case, enqueue() is wrapped by celery.group(). The issue was solved by writing the code like so:

    # tasks.py
    ...
    import os
    # set up celery...
    from celery import group
    from twisted.internet import reactor, ProcessProtocol
    from crochet import setup, wait_for
    ...

    @app.task('tasks.enqueue')
    def enqueue(script_name, command):
        setup()
        try:
            proc = ProcessProtocol()
            proc.deferred.addCallBack(lamda x: x)
            env  = os.environ.copy()
            prints "About to run async process"
            run_async_process(proc, script_name, command, env)
            return proc.exitcode
        except Exception as e:
            print e

After discussing the issue with itamarst and implementing the fix, the issue is believed to be caused when forked Celery processes failing to start the reactor loop. By moving the setup() call into the parent of the function that calls the reactor API, and ONLY calling setup() there, the problem is circumvented.

Be aware that this may have broader implications for code that forks processes and utilizes crochet.setup().

**Comment by itamarst** [comment]
There's a few ways Crochet can solve this:
1. Have `setup()` notice that you've forked since last time it was called, in which case it'll actually do setup instead of being a no-op. This still requires `setup()` be called in all processes, but makes it more robust.
2. Have a post-fork hook that reinitializes Crochet automatically. Transparent to users, but also tricky to do right (and e.g. slows down launching subprocesses).
3. Every Crochet call that relies on initialization detects if a fork happened, and if it has re-initializes Crochet. Slows down crochet calls but maybe not significantly.

**Comment by itamarst** [comment]
After further thought: I don't think it's possible to make this work. Best one can do is document that one can either initialize in parent or children, but not both.

**Comment by bobbyrussell** [comment]
Noted. I guess that the issue should be closed and marked as Won't Fix.
