### ISSUE TITLE
calling a twisted server running on different machine from a pyramid app

### ISSUE THREAD

**Issue by diverdude** [itamarst/crochet#76]
Is it possible to use crochet to call a service on a twistd server running on a different machine from a within a view on a pyramid app?

**Comment by itamarst** [comment]
1. Twisted is a generic networking library.
2. Twisted can therefore e.g. run a HTTP client talking to a HTTP server on a remote machine; the remote server may or may not be Twisted based.
3. Crochet lets you use Twisted with e.g. Pyramid apps very easily.

So: yes, but it's irrelevant to some extent if the remote server is using Twisted. Twisted supports many protocols some of which are also implemented by other libraries. You could also just use e.g. `requests` Python library in Pyramid to send HTTP requests to a remote Twisted server running a HTTP server. Crochet may be better in some ways than doing that, but it depends very much on your use case.
