### ISSUE TITLE
Problem using spawnProcess() with crotchet

### ISSUE THREAD

**Issue by chintal** [itamarst/crochet#91]
I'm having some trouble using crochet with twisted's spawnProcess. The process seems to run when just using twisted, but with crochet, only the protocol's connectionMade function is ever called and the script exits immediately (much faster than the child process would have taken if it was run). Am I doing something wrong?

Relevant portions of the code :

    from crochet import setup, run_in_reactor
    from twisted.internet import reactor
    
    class BareQDAL41xBFactory(Factory):
        def __init__(self):
            self.instances = []

        def buildProtocol(self, port=None, buffer_size=100):
            instance = ProtocolBareQDAL41xB(buffer_size=buffer_size)
            reactor.spawnProcess(instance, BIN_PATH, [BIN_NAME], {})
            return instance

    factory = BareQDAL41xBFactory()

    @run_in_reactor
    def run():
        protocol = factory.buildProtocol()
        return protocol

    # This does not work
    if __name__ == '__main__':
        setup()
        run()

    # This does
    if __name__ == '__main__':
        protocol = factory.buildProtocol()
        reactor.run()

**Comment by itamarst** [comment]
In theory it should work, though with slow notification of process exit.

1. What version Crochet?
2. What OS?

**Comment by chintal** [comment]
A minimal working example that should (hopefully) only need crochet and twisted is up at 
https://gist.github.com/chintal/6014e20a4cac6cebf51e

I suspect the problem has to do with how I'm naming / calling the binary in reactor.spawnProcess(). While trying to set up the MWE , I realize that it works with system binaries. With BIN_NAME, BIN_PATH both 'dmesg', it seems to work as expected. Since my binary is never going to exit, I wrote a small C++ program that just infinitely generates lines. With binary for the following C++ code, though, I seem to be unable to get the MWE to run with either crochet or twisted : 

    #include <iostream>
    #include <unistd.h>

    using namespace std;

    int main() { 
      int i = 0;
      while(1){
        i ++;
        cout << "Line "
	     << i
             << '\n';
        usleep(1000000);
      }
      return 0;
    }

I compiled the above with `g++ test.cpp -o testbin` and put it into /usr/local/bin. Changing BIN_NAME and BIN_PATH to `testbin` makes both of them exit with status 1. 

    $ ls -l /usr/local/bin/testbin 
    -rwxrwxr-x 1 chintal chintal 9207 Aug 27 22:08 /usr/local/bin/testbin

And the example outputs : 

    $ testbin 
    Line 1
    Line 2
    Line 3
    Line 4
    ^C
    $ python test.py 
    Using Twisted
    BIN_PATH testbin
    BIN_NAME testbin
    Made Connection
    processExited, status 1
    processEnded, status 1
    ^C
    $ python test.py
    Using Crochet
    BIN_PATH testbin
    BIN_NAME testbin
    Made Connection
    processExited, status 1
    processEnded, status 1
    $ python test.py
    Using Crochet
    BIN_PATH dmesg
    BIN_NAME dmesg
    Made Connection
    Got data :  [    1.050664] xhci_hcd 0000:00:14.0: xHCI Host Controller
    ...
    [379047.950528] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

    processExited, status 0
    processEnded, status 0
    
And with the original (un-pared down script, the 'Using Twisted' output is as expected)
    
    $ time python BareQDAL41xB.py 
    Using Twisted
    BIN_PATH /media/ldata/koala-qtpl/instruments/bin/BareQDAL41xB
    BIN_NAME BareQDAL41xB
    Made Connection
    Got data : No device found!
    Multiple devices found! Please connect only one.
    
    Got Serial Number :  found!
    Definite error in line : 1:Multiple devices found! Please connect only one.
    processExited, status 0
    processEnded, status 0
    ^C
    real    0m2.726s (# Ctrl+C as soon as the status 0 is seen, maybe a human latency of a second at most)
    user    0m0.108s
    sys     0m0.044s
    $ time python BareQDAL41xB.py 
    Using Crochet
    BIN_PATH /media/ldata/koala-qtpl/instruments/bin/BareQDAL41xB
    BIN_NAME BareQDAL41xB
    Made Connection

    real    0m0.232s
    user    0m0.100s
    sys     0m0.038s
    

The following are the versions I'm using : 

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2

Linux 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Twisted==15.3.0
crochet==1.4.0

**Comment by chintal** [comment]
I think I've figured out what the problem was. The script was falling off the bottom of the script soon after the @run_in_reactor call, which was presumably making the reactor shut down. A while True: pass in the main function after crochet setup and creating the protocol and calling reactor.spawnProcess seems to keep the interpreter, and the managed reactor alive. I expect that if I were actually using the protocol's output instead of just testing it all on it's own, this problem is unlikely to have shown up.

In order to parse the example C++ script in the previous comment, the following changes needed to be made besides the while True in main : 

  - The BIN_PATH actually needs to be the full, absolute path. If it isn't, it results in an OSError Exception that gets eaten up unless usePTY is true.
  - usePTY needs to be true, if not STDOUT also gets eaten up for some reason.
