### ISSUE TITLE
crochet.tests.test_api.EventualResultTests.test_later_success_result is flaky in Python 3

### ISSUE THREAD

**Issue by allenap** [itamarst/crochet#92]
About half the time `test_later_success_result` fails in Python 3:

```
[ERROR]
Traceback (most recent call last):
  File ".../crochet/tests/test_api.py", line 130, in test_later_success_result
    self.assertEqual(dr.wait(), 345)
  File ".../crochet/_eventloop.py", line 229, in wait
    result = self._result(timeout)
  File ".../crochet/_eventloop.py", line 193, in _result
    raise TimeoutError()
crochet._eventloop.TimeoutError: 

crochet.tests.test_api.EventualResultTests.test_later_success_result
```

Using Twisted 15.4.0 in a --no-site-packages virtualenv on Ubuntu Wily.

**Comment by itamarst** [comment]
Thanks for the bug report! I'll see if I can figure it out. On Travis-CI at least I've never seen that, so hopefully it's just the test that's buggy.

**Comment by itamarst** [comment]
Unable to reproduce this locally (Python 3.5, Twisted==15.4.0), so next I will try to see if I can spot an issue by reading the code.

**Comment by itamarst** [comment]
Ah, non-threadsafe operations here and in a couple of other tests.
